version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - ./src:/app
    ports:
      - "8002:8002"

    environment:
      - DJANGO_SETTINGS_MODULE=article_microservice.settings
