# Generated by Django 5.0.6 on 2024-05-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='role',
        ),
    ]
